/*
	A basic extension of the java.applet.Applet class
 */

import java.awt.*;
import java.applet.*;
import java.awt.event.*;

/**
 * @version 1.0 Oct 1997
 * @author Alex Chaffee (<a href="mailto:alex@stinky.com">alex@stinky.com</a>)
 */
public class RmiChatApplet extends Applet implements ActionListener
{

    AppletChatClient client;

	public void init()
	{

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setSize(426,266);
		textSend = new java.awt.TextField();
		textSend.setBounds(12,228,312,24);
		add(textSend);
		buttonSend = new java.awt.Button();
		buttonSend.setActionCommand("button");
		buttonSend.setLabel("Send");
		buttonSend.setBounds(348,228,60,28);
		buttonSend.setBackground(new Color(12632256));
		add(buttonSend);
		textArea = new java.awt.TextArea();
		textArea.setEditable(false);
		textArea.setBounds(12,36,396,180);
		add(textArea);
		labelTitle = new java.awt.Label("RMI Chat by Alex Chaffee");
		labelTitle.setBounds(12,12,396,12);
		labelTitle.setFont(new Font("Dialog", Font.BOLD, 12));
		add(labelTitle);
		//}}

        // create client object
        String url = "rmi://" + getCodeBase().getHost() + "/ChatServer";
        try {
            client = new AppletChatClient(url, this);
        }
        catch (java.rmi.RemoteException re) {
            re.printStackTrace();
            textArea.append(re.toString() + "\n");
        }

	    // register for events
	    buttonSend.addActionListener(this);
	    textSend.addActionListener(this);

	}

	//{{DECLARE_CONTROLS
	java.awt.TextField textSend;
	java.awt.Button buttonSend;
	java.awt.TextArea textArea;
	java.awt.Label labelTitle;
	//}}

	public void actionPerformed(ActionEvent e) {
	    if (e.getSource() == buttonSend || e.getSource() == textSend)
	    {
	        String message = textSend.getText();
	        if (!message.equals(""))
	        {
	            try {
    	            client.sendString(message);
    	        }
    	        catch (java.rmi.RemoteException re) {
    	            re.printStackTrace();
    	            textArea.append(re.toString() + "\n");
    	        }
	        }
	    }
	}
}
